### ISSUE TITLE
(Posible) Error en "Introducción a .NET y C#" > "Apuntes" > "Sentencias de iteración"

### ISSUE THREAD

**Issue by JuanCruzMz** [codeutnfra/programacion_2_laboratorio_2_apuntes#1]
Hola. 

Primera vez que reporto un error y de todas formas no estoy seguro de si me ocurrirá solo a mí, pero revisando los apuntes de la primera clase, por alguna razón no estoy pudiendo ver los ejemplos de cómo deberían escribirse las sentencias "while", "do-while", "for" y "foreach". Solo se muestra el título de cada sección ("Sentencia while", "Sentencia do-while", etc.), sus respectivos tips y nada más.

![Captura de pantalla (799)](https://user-images.githubusercontent.com/52410653/131409517-e8a0c6ce-5e49-40bf-b6eb-ac87b79e90c8.png)

**Comment by mauricioCerizza** [comment]
Hola Juan!! Está incompleto, tenés razón. Lo arreglaremos en breve.

**Comment by JuanCruzMz** [comment]
Ah, perfecto. Muchas gracias!
